dataset: NONE
ext_1: !include:ext_1.yaml
  name: test
ext_2: !include:ext_2.yaml
ext_3: !include:ext_3.yaml
  new_key: a_new_key


#ext_4: !include:ext_4.yaml

test_output:
  ext_1: !ref <ext_1>
  ext_2: !ref <ext_2>
  ext_3: !ref <ext_3>
#  ext_4: !ref <ext_4>