n_epochs: 50

epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
    limit: !ref <n_epochs>


normalizer: !new:speechbrain.processing.features.InputNormalization
    norm_type: global

metric_keys:
    - accuracy.average

max_key: flvl_md.F1


####################################

# Training parameters
number_of_epochs: 10
lr: 0.0003
#lr: 0.001

# HMM parameters
states_per_phoneme: 3

# Outputs
output_neurons: !ref <states_per_phoneme> * (<n_phonemes> + 2)
blank_index: !ref <output_neurons> - 1

# Model parameters
activation: !name:torch.nn.LeakyReLU
dnn_blocks: 1
dnn_neurons: 2000

init_training_type: 'forward' # 'forward' or 'viterbi' or 'ctc'
switch_training_type: 'forward'
switch_training_epoch: 2

model: !new:speechbrain.lobes.models.VanillaNN.VanillaNN
    input_shape: [null, null, !ref <input_size>]
    dnn_blocks: !ref <dnn_blocks>
    dnn_neurons: !ref <dnn_neurons>
    activation: !ref <activation>

output: !new:speechbrain.nnet.linear.Linear
    input_size: !ref <dnn_neurons>
    n_neurons: !ref <output_neurons>
    bias: True

log_softmax: !new:speechbrain.nnet.activations.Softmax
    apply_log: True

aligner: !new:speechbrain.alignment.aligner.HMMAligner
    states_per_phoneme: !ref <states_per_phoneme>
    batch_reduction: 'mean'
    input_len_norm: True
    target_len_norm: False

optimizer: !name:torch.optim.Adam
    lr: !ref <lr>

lr_annealing: !new:speechbrain.nnet.schedulers.NewBobScheduler
    initial_value: !ref <lr>
    improvement_threshold: 5
    annealing_factor: 1.0
    patient: 0

modules:
    model: !ref <model>
    output: !ref <output>
    aligner: !ref <aligner>

checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
    checkpoints_dir: !ref <output_dir>/checkpoints
    recoverables:
        model: !ref <model>
        output: !ref <output>
        scheduler: !ref <lr_annealing>
        counter: !ref <epoch_counter>


compute_cost_ctc: !name:speechbrain.nnet.losses.ctc_loss
    blank_index: !ref <blank_index>

compute_cost_nll: !name:speechbrain.nnet.losses.nll_loss
