n_epochs: 50

epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
    limit: !ref <n_epochs>

checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
    checkpoints_dir: !ref <output_dir>/checkpoints
    recoverables:
        normalizer: !ref <normalizer>
        lstm: !ref <lstm>
        fc: !ref <fc>
        epoch_counter: !ref <epoch_counter>

normalizer: !new:speechbrain.processing.features.InputNormalization
    norm_type: global

# model parameters
misp_weight: 10

lstm_hidden_size: 1024
lstm_num_layers: 4
lstm_dropout: 0.1
lstm: !new:torch.nn.LSTM
    batch_first: True
    input_size: !ref <input_size>
    hidden_size: !ref <lstm_hidden_size>
    num_layers: !ref <lstm_num_layers>
    dropout: !ref <lstm_dropout>

fc_size: 64
fc_dropout: 0
output_size: 2
fc: !new:modules.fc_block.FCBlock
    fc_sizes:
        - !ref <lstm_hidden_size>
        - !ref <fc_size>
        - !ref <fc_size>
        - !ref <output_size>
    dropout: !ref <fc_dropout>


log_softmax: !new:speechbrain.nnet.activations.Softmax
    apply_log: True

lr: 1.0
optimizer: !name:torch.optim.Adam
    lr: !ref <lr>

modules:
    normalizer: !ref <normalizer>
    lstm: !ref <lstm>
    fc: !ref <fc>

# evaluation metrics
metric_keys:
    - flvl_md.ACC
    - flvl_md.PRE
    - flvl_md.REC
    - flvl_md.F1

max_key: flvl_md.F1
