
n_epochs: 50

epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
    limit: !ref <n_epochs>

# Model parameters
lstm_hidden_size: 1024
lstm_num_layers: 4
lstm_dropout: 0.1
fc_size: 64
fc_dropout: 0
fc_num_layers: 2

misp_weight: 10

output_size: 2

normalizer: !new:speechbrain.processing.features.InputNormalization
    norm_type: global

#lstm: !new:torch.nn.LSTM
#    batch_first: True
#    input_size: !ref <input_size>
#    hidden_size: !ref <lstm_hidden_size>
#    num_layers: !ref <lstm_num_layers>
#    dropout: !ref <lstm_dropout>
#
#fc: !new:blocks.fc_block.FCBlock
#    input_size: !ref <lstm_hidden_size>
#    fc_size: !ref <fc_size>
#    dropout: !ref <fc_dropout>
#    num_layers: !ref <fc_num_layers>
#
#output: !new:torch.nn.Linear
#    in_features: !ref <fc_size>
#    out_features: !ref <output_size>

#log_softmax: !new:speechbrain.nnet.activations.Softmax
#    apply_log: True
#
#optimizer: !name:torch.optim.Adam
#    lr: !ref <lr>


compute_cost: !name:speechbrain.nnet.losses.ctc_loss
ctc_stats: !name:speechbrain.utils.metric_stats.MetricStats
per_stats: !name:speechbrain.utils.metric_stats.ErrorRateStats
md_stats: !name:utils.md_metric_stats.MDMetricStats


#checkpoints_dir: !ref <output_dir>/checkpoints
#checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
#    checkpoints_dir: !ref <checkpoints_dir>
#    recoverables:
#        normalizer: !ref <normalizer>
#        lstm: !ref <lstm>
#        fc: !ref <fc>
#        output: !ref <output>
#        epoch_counter: !ref <epoch_counter>


metric_keys:
#    - per.error_rate
    - flvl_md.ACC
    - flvl_md.PRE
    - flvl_md.REC
    - flvl_md.F1

max_key: flvl_md.F1


# ################################
# Model: seq2seq ASR on TIMIT with wav2vec2 + CTC/Attention
# Authors:
# * Titouan Parcollet 2021
# ################################

# URL for the biggest Fairseq english wav2vec2 model.
wav2vec2_hub: "facebook/wav2vec2-large-lv60"

# Training parameters
#number_of_epochs: 5
#batch_size: 1  # 8
lr: 0.0003  # ori: 0.0003
lr_wav2vec: 0.0001
#ctc_weight: 0.2
#sorting: ascending
#auto_mix_prec: False
#sample_rate: 16000

## Model parameters
#activation: !name:torch.nn.LeakyReLU
#dnn_layers: 2
#dnn_neurons: 1024
#emb_size: 128
#dec_neurons: 256
freeze_wav2vec: False

## Outputs
#output_neurons: 42 # 39phs+blank+eos+bos # 42
#bos_index: 0
#eos_index: 1
#blank_index: 2
#
## Decoding parameters
#min_decode_ratio: 0.0
#max_decode_ratio: 1.0
#beam_size: 16
#eos_threshold: 1.5

#enc: !new:speechbrain.lobes.models.VanillaNN.VanillaNN
#    input_shape: [null, null, 1024]
#    activation: !ref <activation>
#    dnn_blocks: !ref <dnn_layers>
#    dnn_neurons: !ref <dnn_neurons>

wav2vec2: !new:speechbrain.lobes.models.huggingface_wav2vec.HuggingFaceWav2Vec2
    source: !ref <wav2vec2_hub>
    output_norm: True
    freeze: !ref <freeze_wav2vec>
    save_path: !ref <output_dir>/wav2vec2_checkpoint

#classifier: !new:speechbrain.nnet.linear.ClassLinear
#    ninput: 1024
#    nout: 1
#    nhidden1: 512
#    nhidden2: 128

classifier: !new:blocks.fc_block.FCBlock
    fc_sizes:
        - 1024
        - 512
        - 128
        - 1
#    dropout: !ref <fc_dropout>

bin_cost: !name:speechbrain.nnet.losses.bce_loss

bin_stats: !name:speechbrain.utils.metric_stats.MetricStats
    metric: !name:speechbrain.nnet.losses.bce_loss
#####
# Uncomment this block if you prefer to use a Fairseq pretrained model instead
# of a HuggingFace one. Here, we provide an URL that is obtained from the
# Fairseq github for an equivalent model compared to HuggingFace.
#
# wav2vec2_url: https://dl.fbaipublicfiles.com/fairseq/wav2vec/wav2vec_vox_new.pt
# wav2vec2: !new:speechbrain.lobes.models.fairseq_wav2vec.FairseqWav2Vec2
#     pretrained_path: !ref <wav2vec2_url>
#     output_norm: True
#     freeze: False
#     save_path: !ref <save_folder>/wav2vec2_checkpoint/model.pt
#####

adam_opt_class: !name:torch.optim.Adam
    lr: !ref <lr>

wav2vec_opt_class: !name:torch.optim.Adam
    lr: !ref <lr_wav2vec>

optimizer: !ref <adam_opt_class>

lr_annealing_adam: !new:speechbrain.nnet.schedulers.NewBobScheduler
    initial_value: !ref <lr>
    improvement_threshold: 0.0025
    annealing_factor: 0.8
    patient: 0

lr_annealing_wav2vec: !new:speechbrain.nnet.schedulers.NewBobScheduler
    initial_value: !ref <lr_wav2vec>
    improvement_threshold: 0.0025
    annealing_factor: 0.9

modules:
    wav2vec2: !ref <wav2vec2>
    classifier: !ref <classifier>

checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
  checkpoints_dir: !ref <output_dir>/checkpoints
  recoverables:
        classifier: !ref <classifier>
        wav2vec2: !ref <wav2vec2>
        lr_annealing_adam: !ref <lr_annealing_adam>
        lr_annealing_wav2vec: !ref <lr_annealing_wav2vec>
        counter: !ref <epoch_counter>

#train_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
#    save_file: !ref <train_log>

# ctc_stats: !name:speechbrain.utils.metric_stats.MetricStats
#     metric: !name:speechbrain.nnet.losses.ctc_loss
#         blank_index: !ref <blank_index>
#         reduction: batch

# seq_stats: !name:speechbrain.utils.metric_stats.MetricStats
#     metric: !name:speechbrain.nnet.losses.nll_loss
#         label_smoothing: 0.1
#         reduction: batch

# per_stats: !name:speechbrain.utils.metric_stats.ErrorRateStats