n_epochs: 50
lr: 0.1
lr_wav2vec: 0.0001

epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
    limit: !ref <n_epochs>
# Model parameters
activation: !name:torch.nn.LeakyReLU
dropout: 0.15
cnn_blocks: 2
cnn_channels: (128, 128)
cnn_kernelsize: (3, 3)
rnn_layers: 2
rnn_neurons: 512
rnn_bidirectional: True
dnn_blocks: 2
dnn_neurons: 128


# Outputs
output_neurons: !ref <n_phonemes> + 2

wav2vec2: !new:speechbrain.lobes.models.huggingface_wav2vec.HuggingFaceWav2Vec2
    source: "facebook/wav2vec2-large-lv60"
    output_norm: True
    freeze: False
    save_path: !ref <output_dir>/wav2vec2_checkpoint

crdnn: !new:speechbrain.lobes.models.CRDNN.CRDNN
    input_size: 1024
    activation: !ref <activation>
    dropout: !ref <dropout>
    cnn_blocks: !ref <cnn_blocks>
    cnn_channels: !ref <cnn_channels>
    cnn_kernelsize: !ref <cnn_kernelsize>
    time_pooling: True
    rnn_layers: !ref <rnn_layers>
    rnn_neurons: !ref <rnn_neurons>
    rnn_bidirectional: !ref <rnn_bidirectional>
    dnn_blocks: !ref <dnn_blocks>
    dnn_neurons: !ref <dnn_neurons>

output: !new:speechbrain.nnet.linear.Linear
    input_size: !ref <dnn_neurons>
    n_neurons: !ref <output_neurons>
    bias: True

log_softmax: !new:speechbrain.nnet.activations.Softmax
    apply_log: True

optimizers:
    adam_opt:
        opt_class: !name:torch.optim.Adadelta
            rho: 0.95
            lr: !ref <lr>
            eps: 1.e-8
        modules:
            - crdnn
            - output
    wav2vec_opt:
        opt_class: !name:torch.optim.Adam
            lr: !ref <lr_wav2vec>
        modules:
            - wav2vec2

scheduler: !new:speechbrain.nnet.schedulers.NewBobScheduler
    initial_value: !ref <lr>
    improvement_threshold: 0.0025
    annealing_factor: 0.8
    patient: 0

modules:
    wav2vec2: !ref <wav2vec2>
    crdnn: !ref <crdnn>
    output: !ref <output>

compute_cost: !name:speechbrain.nnet.losses.ctc_loss

checkpoints_dir: !ref <output_dir>/checkpoints
checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
    checkpoints_dir: !ref <checkpoints_dir>
    recoverables:
        wav2vec2: !ref <wav2vec2>
        crdnn: !ref <crdnn>
        output: !ref <output>
        scheduler: !ref <scheduler>
        epoch_counter: !ref <epoch_counter>


wer_file: !ref <output_dir>/wer.txt
md_metrics_file: !ref <output_dir>/md_metrics.txt

metric_keys:
    - phn_per.error_rate
    - cnncl_per.error_rate
    - plvl_md.ACC
    - plvl_md.PRE
    - plvl_md.REC
    - plvl_md.F1

max_key: plvl_md.F1

jit_module_keys: [crdnn]